/**:
  ros__parameters:
    # --- Physical Configs ---
    camera_x_to_body_east_sign: 1.0
    camera_y_to_body_north_sign: -1.0
    camera_yaw_frame: "body"
    camera_offset_x: 0.157
    camera_offset_y: 0.0
    camera_offset_z: -0.15
    marker_size: 0.50
    camera_mount_roll: 180.0
    camera_mount_pitch: 0.0
    camera_mount_yaw: -90.0

    # --- Dynamic Gates ---
    align_r_min: 0.25
    align_r_max: 4.0
    align_r_gain: 0.20
    align_r_bias: 0.15
    desc_r_min: 0.15
    desc_r_max: 2.0
    desc_r_gain: 0.15
    desc_r_bias: 0.12
    reject_r_min: 1.0
    reject_r_max: 5.0
    reject_r_gain: 0.50

    high_alt: 8.0
    low_alt: 5.0
    alpha_high: 0.15
    alpha_low: 0.55
